language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_docs.txt
  - pip install .

script:
  - make test

after_success:
  - make doc

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: docs/build/html
  committer-from-gh: true
  verbose: true
